### ISSUE TITLE
Magento2 in php 5.6

### ISSUE THREAD

**Issue by gsc-dev** [EcomDev/fast-hypernode#2]
I am required to install Magento 2 on php 5.6 since we use extensions built by Zend-Gard, which only support version 5.6

http://files.zend.com/help/Zend-Guard/content/install.htm

Would you have a box using that version?

```
    config.vm.box = 'hypernode_php5'
    config.vm.box_url = 'http://vagrant.hypernode.com/customer/php5/catalog.json'
```

If not, how can I upgrade the current one?

**Comment by IvanChepurnyi** [comment]
There is no way to install php5.6 as base box does not support that:
https://github.com/ByteInternet/hypernode-vagrant/issues/26

**Comment by IvanChepurnyi** [comment]
As mentioned by ByteInternet, they are not planning to support 5.6 and advice everyone to migrate to PHP7.0
